#!/usr/bin/env python
# -*- coding: utf-8 -*-

from argparse import ArgumentParser, FileType
import os
import json
import logging

parser = ArgumentParser()
parser.add_argument('-v', '--verbose', action='count')
parser.add_argument('source', type=FileType('r'))
parser.add_argument('target', type=FileType('w'))
args = parser.parse_args()

lvl = ['ERROR', 'WARN', 'INFO', 'DEBUG'][max(0, min(2 if args.verbose==None else args.verbose, 3))]
logging.basicConfig(format='%(asctime)s [%(levelname)s] %(message)s', datefmt='%FT%T', level=lvl)

logging.debug('open source: %s', args.source.name)
logging.debug('open target: %s', args.target.name)

ok = err = 0

for line in args.source:
    try:
        line = line.strip()
        logging.debug('process: %s', line)
        obj = json.loads(line)
        args.target.write(line+'\n')
        ok += 1
    except Exception as ex:
        logging.warn('cannot decode: %s (%s)', line, ex)
        err += 1

logging.info(u'success: %d, failed: %d', ok, err)
logging.debug('close source: %s', args.source.name)
logging.debug('close target: %s', args.target.name)

args.source.close()
args.target.close()

