#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from argparse import ArgumentParser, FileType
from os.path import exists
from lxml import html, etree
import sys
import requests

parser = ArgumentParser()
parser.add_argument('xpath', metavar='EXPR')
parser.add_argument('files', metavar='FILE', nargs='+')
args = parser.parse_args()

ns = {
    "re": "http://exslt.org/regular-expressions"
}

for uri in args.files:

    if uri.startswith('http://'):
        txt = requests.get(uri).text
    elif exists(uri):
        txt = open(uri).read()
    else:
        print('%s: cannot access %s'%(sys.argv[0], uri), file=sys.stderr)
        continue

    dom = html.fromstring(txt)

    for e in dom.xpath(args.xpath, namespaces=ns):
        if isinstance(e, html.HtmlElement):
            print(etree.tostring(e, encoding='utf-8').decode())
        else:
            print(e)

